using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// Programmer : David Fletcher
// Last Edited : 09 / 25 / 2014
// V 1.0
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
// Solution : 233168
namespace Project_Euler
{
    class Even_Fibonacci
    {
        public static void Entry()
        {
            Console.WriteLine("Project Euler : Problem 2");
            Console.WriteLine("Even Fibonacci Numbers");

            Console.WriteLine("Solution : {0}", Fibonacci(4000000));
        }

        /// <summary>
        /// Where the math of the problem takes place
        /// Iterate through the Fibonacci Sequence until cap is reached
        /// add up any even-valued terms
        /// </summary>
        /// <param name="cap">input the cap that it wants for the while loop</param>
        /// <returns>solution to problem</returns>
        private static int Fibonacci(int cap)
        {
            int oldVal = 0, newVal = 1;
            int temp = 0, total = 0;

            // iterate until cap is reached
            while (temp < cap)
            {
                temp = oldVal + newVal;
                oldVal = newVal;
                newVal = temp;
                
                // check if term is even
                if (temp % 2 == 0)
                {
                    total = total + temp;
                }

            }
            return total;
        }
    }
}
